module.exports = Object.freeze({
    E_UnknownRoute: 'E-UnknownRoute',
    E_UnknownError: 'E-UnknownError',
    E_WrongCredentials: 'E-WrongCredentials',
    E_NoToken: 'E-NoToken',
    E_Unauthorized: 'E-Unauthorized',
    E_NoResource: 'E-NoResource',
    E_AgeTooYoung: 'E-AgeTooYoung',
    E_BadEmailFormat: 'E-BadEmailFormat',
    E_EmailKnown: 'E-EmailKnown',
    E_DatabaseDataTooLong: 'E-DatabaseDataTooLong',
    E_EmailTooLong: 'E-EmailTooLong',
    E_PasswordTooLong: 'E-PasswordTooLong',
    E_PasswordTooShort: 'E-PasswordTooShort',
    E_SurnameTooLong: 'E-SurnameTooLong',
    E_FirstNameTooLong: 'E-FirstNameTooLong',
    S_Success: 'S-Success',
});
